version: 2.1
jobs:
  build:
    environment:
      BUILD_VERSION: 1.0.32
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:3.1-alpine
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Git
          command: apk add git
      - run:
          name: Clone GraphLinq.Engine
          command: git clone https://github.com/GraphLinq/GraphLinq.Engine.git ../GraphLinq.Engine
      - run:
          name: Clone GraphLinq.Encoding
          command: git clone https://github.com/GraphLinq/GraphLinq.Encoding.git ../GraphLinq.Encoding
      - run:
          name: Restore
          command: dotnet restore
      - run:
          name: Build
          command: dotnet build -c Release
      - run:
          name: Install docker
          command: |
              apk add --update docker openrc
              rc-update add docker boot
            
      - run:
          name: Build docker
          command: |
            	rm -rf docker_build
              mkdir docker_build
              echo "Create plugin directory"
              mkdir docker_build/plugins
              cp -a bin/Release/netcoreapp3.1/. docker_build/
              docker build -t graphlinqcli .
      - run:
          name: Push Docker Hub
          command: |
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker tag graphlinqcli:latest graphlinq/graphlinq-engine:ci
            docker push graphlinq/graphlinq-engine:ci
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
